# Generated by Django 5.0.7 on 2024-07-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock1', models.CharField(max_length=255)),
                ('stock2', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('entry', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_diff', models.CharField(max_length=10)),
                ('exit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_diff', models.CharField(max_length=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss_diff', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
